# Generated by Django 5.1.4 on 2024-12-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
    ]
